#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════
# P3 Bridge — PC-side Setup Script (install_pc.sh)
#
# This script sets up everything needed on the PC:
#   1. Creates ~/.p3/ config directory
#   2. Installs bridge client as systemd service
#   3. Validates GitHub PAT
#   4. Sets up audit log directory
#
# Usage:
#   chmod +x install_pc.sh
#   ./install_pc.sh --token <GITHUB_PAT> [options]
# ════════════════════════════════════════════════════════════════

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║          P³ Bridge — PC Setup (install_pc.sh)        ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ──────────────────────── Parse Args ────────────────────────

TOKEN=""
SECRET=""
REPO_OWNER="Kotokvit"
REPO_NAME="p3-agent-cell"
SECURITY_MODE="blacklist"
RATE_LIMIT=30
POLL_INTERVAL=10
ENGINE_DIR=""
INSTALL_DIR="$HOME/.p3"

while [[ $# -gt 0 ]]; do
    case $1 in
        --token)       TOKEN="$2"; shift 2 ;;
        --secret)      SECRET="$2"; shift 2 ;;
        --repo-owner)  REPO_OWNER="$2"; shift 2 ;;
        --repo-name)   REPO_NAME="$2"; shift 2 ;;
        --security)    SECURITY_MODE="$2"; shift 2 ;;
        --rate-limit)  RATE_LIMIT="$2"; shift 2 ;;
        --poll)        POLL_INTERVAL="$2"; shift 2 ;;
        --engine-dir)  ENGINE_DIR="$2"; shift 2 ;;
        --install-dir) INSTALL_DIR="$2"; shift 2 ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

if [[ -z "$TOKEN" ]]; then
    echo -e "${RED}ERROR: --token is required${NC}"
    echo "Usage: ./install_pc.sh --token <GITHUB_PAT> [--secret <SHARED_SECRET>]"
    exit 1
fi

# ──────────────────────── Step 1: Config Dir ────────────────────────

echo -e "${BLUE}[1/6]${NC} Creating config directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/bridge"
mkdir -p "$INSTALL_DIR/logs"

# ──────────────────────── Step 2: Validate Token ────────────────────────

echo -e "${BLUE}[2/6]${NC} Validating GitHub PAT..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "Authorization: token $TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/user")

if [[ "$HTTP_CODE" == "200" ]]; then
    USERNAME=$(curl -s -H "Authorization: token $TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/user" | python3 -c "import sys,json; print(json.load(sys.stdin)['login'])" 2>/dev/null || echo "unknown")
    echo -e "  ${GREEN}✓${NC} Token valid — authenticated as: $USERNAME"
else
    echo -e "  ${RED}✗${NC} Token validation failed (HTTP $HTTP_CODE)"
    echo "  Make sure the PAT has 'repo' and 'gist' scopes"
    exit 1
fi

# Check write access to repo
WRITE_CHECK=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "Authorization: token $TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME")

if [[ "$WRITE_CHECK" == "200" ]]; then
    echo -e "  ${GREEN}✓${NC} Repo access: $REPO_OWNER/$REPO_NAME"
else
    echo -e "  ${YELLOW}⚠${NC} Cannot access repo: $REPO_OWNER/$REPO_NAME (HTTP $WRITE_CHECK)"
    echo "  Creating repo..."
    if [[ "$REPO_OWNER" == "$USERNAME" ]]; then
        curl -s -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"name\":\"$REPO_NAME\",\"private\":false,\"auto_init\":true}" \
            "https://api.github.com/user/repos" > /dev/null
        echo -e "  ${GREEN}✓${NC} Repo created"
    else
        echo -e "  ${RED}✗${NC} Cannot create repo in another user's account"
        exit 1
    fi
fi

# ──────────────────────── Step 3: Copy Bridge Files ────────────────────────

echo -e "${BLUE}[3/6]${NC} Installing bridge client..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp "$SCRIPT_DIR/bridge/p3_client.py" "$INSTALL_DIR/bridge/"
cp "$SCRIPT_DIR/bridge/p3_security.py" "$INSTALL_DIR/bridge/"
chmod +x "$INSTALL_DIR/bridge/p3_client.py"
echo -e "  ${GREEN}✓${NC} Bridge files installed to $INSTALL_DIR/bridge/"

# ──────────────────────── Step 4: Config File ────────────────────────

echo -e "${BLUE}[4/6]${NC} Writing configuration..."

cat > "$INSTALL_DIR/config.env" << EOF
# P3 Bridge Configuration — generated by install_pc.sh
# Edit this file to change settings

P3_GITHUB_TOKEN=$TOKEN
P3_REPO_OWNER=$REPO_OWNER
P3_REPO_NAME=$REPO_NAME
P3_SECURITY_MODE=$SECURITY_MODE
P3_RATE_LIMIT=$RATE_LIMIT
P3_SECRET=$SECRET
P3_ENGINE_DIR=$ENGINE_DIR
P3_AUDIT_DIR=$INSTALL_DIR/logs
EOF

chmod 600 "$INSTALL_DIR/config.env"  # Only owner can read (has token!)
echo -e "  ${GREEN}✓${NC} Config written to $INSTALL_DIR/config.env (chmod 600)"

# ──────────────────────── Step 5: Audit Log Setup ────────────────────────

echo -e "${BLUE}[5/6]${NC} Setting up audit logging..."
mkdir -p /var/log/p3-bridge 2>/dev/null || mkdir -p "$INSTALL_DIR/logs"
echo -e "  ${GREEN}✓${NC} Audit logs: ${INSTALL_DIR}/logs/"

# ──────────────────────── Step 6: Systemd Service ────────────────────────

echo -e "${BLUE}[6/6]${NC} Installing systemd service..."

CWD_ARG=""
if [[ -n "$ENGINE_DIR" ]]; then
    CWD_ARG="--cwd $ENGINE_DIR"
fi

cat > "$INSTALL_DIR/p3-bridge-client.service" << EOF
[Unit]
Description=P3 Bridge Client — Remote Command Bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 $INSTALL_DIR/bridge/p3_client.py --token \$(cat $INSTALL_DIR/config.env | grep P3_GITHUB_TOKEN | cut -d= -f2) --poll $POLL_INTERVAL --security $SECURITY_MODE --rate-limit $RATE_LIMIT $CWD_ARG
EnvironmentFile=$INSTALL_DIR/config.env
WorkingDirectory=$INSTALL_DIR/bridge
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=p3-bridge

# Security hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=$INSTALL_DIR/logs /var/log/p3-bridge
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
EOF

# Copy to systemd
sudo cp "$INSTALL_DIR/p3-bridge-client.service" /etc/systemd/system/ 2>/dev/null && \
    sudo systemctl daemon-reload 2>/dev/null && \
    echo -e "  ${GREEN}✓${NC} Systemd service installed" || \
    echo -e "  ${YELLOW}⚠${NC} Could not install systemd service (need sudo). Manual install:"
echo "  sudo cp $INSTALL_DIR/p3-bridge-client.service /etc/systemd/system/"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl enable --now p3-bridge-client"

# ──────────────────────── Summary ────────────────────────

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              Setup Complete! 🎉                      ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Config:    $INSTALL_DIR/config.env"
echo "║  Bridge:    $INSTALL_DIR/bridge/"
echo "║  Logs:      $INSTALL_DIR/logs/"
echo "║  Security:  $SECURITY_MODE mode, $RATE_LIMIT cmds/min"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Start:     sudo systemctl start p3-bridge-client    ║"
echo "║  Status:    sudo systemctl status p3-bridge-client   ║"
echo "║  Logs:      journalctl -u p3-bridge-client -f        ║"
echo "║  Stop:      sudo systemctl stop p3-bridge-client     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ──────────────────────── Quick Start Option ────────────────────────

read -p "Start bridge client now? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Starting bridge client..."
    source "$INSTALL_DIR/config.env"
    python3 "$INSTALL_DIR/bridge/p3_client.py" \
        --token "$TOKEN" \
        --poll "$POLL_INTERVAL" \
        --security "$SECURITY_MODE" \
        --rate-limit "$RATE_LIMIT" \
        $CWD_ARG
fi
